author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /frisky-matron-facebook-group2
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
homepage_image: http://readuxout2in.library.emory.edu/books/emory:4cgcv/pages/emory:gm1zp/single-page/
image_size:
  page:
    height: 1000
    width: 712
  small-thumbnail:
    height: 100
    width: 71
  thumbnail:
    height: 300
    width: 213
permalink: pretty
publication_info:
  author: Lysle, Percy.
  date: '2016'
  editors:
  - Sara Palmer
  - Sara Palmer
  tei_xml: tei.xml
  title: A frisky matron, an annotated digital edition
show_annotation_author: true
source_info:
  author: Lysle, Percy.
  date: '1897'
  pdf_url: http://readuxout2in.library.emory.edu/books/emory:4cgcv/pdf/#page=2
  title: A frisky matron
  url: http://readuxout2in.library.emory.edu/books/emory:4cgcv/
  via_readux: true
tagline: ', an annotated digital edition'
title: A frisky matron
url: http://sarepal.github.io/frisky-matron-facebook-group2/
version: 1.0.0
